#!/usr/bin/env python3
"""Replace the cached gallery images with those generated in a CI run.

The montage (.github/workflows/montage.yml) is built from two sources: the
images produced by the design matrix in CI, and the images committed to
``images/`` for designs that CI cannot run itself. Designs tagged
``"skip_class": "resource"`` in .github/workflows/config/designs.json are
skipped on the default runner (timeouts / out-of-memory) and run instead by the
"Run Large Gallery Designs" workflow on a bigger runner. This script takes such
a run and refreshes ``images/`` from it, so the committed cache matches what the
large runner most recently produced.

Given a run (URL or id) it downloads every gallery image artifact, then makes
``images/`` match the run: images the run produced are added or overwritten, and
cached PNGs the run did not produce are deleted. Non-PNG files (montage.jpg,
regenerated by CI) are left alone. Pass --dry-run to see the changes first, or
--no-prune to keep cached PNGs the run did not produce.

Image filenames come from inside the artifacts rather than from artifact names:
an artifact is named "<design>-<target>-image" but the image inside it is named
"<design>_<jobname>.png", and the jobname is the resolved target (target
"icsprout55_ics55" produces "aes_icsprout55_ics55_stdcell_r.png").

Note the artifact retention in run-designs.yml: the per-design "*-image"
artifacts are kept 2 days and the merged "images" artifact 7 days, so a run
older than that has nothing left to download.

Requires the `gh` CLI to be installed and authenticated.

Examples:
    python3 scripts/update_image_cache.py \\
        https://github.com/siliconcompiler/scgallery/actions/runs/31756009018
    python3 scripts/update_image_cache.py 31756009018 --dry-run
    python3 scripts/update_image_cache.py 31756009018 --no-prune
"""

import argparse
import filecmp
import glob
import json
import os
import shutil
import subprocess
import sys
import tempfile

from triage_failures import (
    DEFAULT_REPO,
    FAILING_CONCLUSIONS,
    fetch_job_results,
    parse_run,
    run_gh,
)

IMAGE_CACHE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "images")

# The merged artifact built by the merge_images job, and the per-design
# artifacts it merges (which survive on their own when a run fails, because
# merge_images is skipped then).
MERGED_ARTIFACT = "images"
PER_DESIGN_SUFFIX = "-image"

PNG_MAGIC = b"\x89PNG\r\n\x1a\n"


def fetch_image_artifacts(run_id, repo):
    """Return ``(live, expired)`` lists of gallery image artifact names."""
    try:
        result = run_gh([
            "api", "--paginate",
            f"repos/{repo}/actions/runs/{run_id}/artifacts?per_page=100",
            "--jq", ".artifacts[] | {name, expired}",
        ])
    except FileNotFoundError:
        sys.exit("error: `gh` CLI not found. Install and authenticate it first.")
    if result.returncode != 0:
        sys.exit(f"error: gh failed:\n{result.stderr.strip()}")

    live, expired = [], []
    for line in result.stdout.splitlines():
        line = line.strip()
        if not line:
            continue
        artifact = json.loads(line)
        name = artifact["name"]
        if name != MERGED_ARTIFACT and not name.endswith(PER_DESIGN_SUFFIX):
            continue
        (expired if artifact["expired"] else live).append(name)
    return live, expired


def download_artifacts(run_id, repo, names, dest):
    """Download the named artifacts into ``dest``."""
    args = ["run", "download", run_id, "--repo", repo, "--dir", dest]
    for name in names:
        args += ["--name", name]
    try:
        result = run_gh(args, timeout=1800)
    except subprocess.TimeoutExpired:
        sys.exit("error: timed out downloading artifacts")
    if result.returncode != 0:
        sys.exit(f"error: gh run download failed:\n{result.stderr.strip()}")


def collect_images(root):
    """Map image basename -> path for every PNG downloaded under ``root``.

    gh nests each artifact's contents under a per-artifact directory when
    several are downloaded at once, and the images themselves sit in a
    SiliconCompiler-version directory, so this searches the whole tree. A
    basename can appear twice when a run has both the merged artifact and the
    per-design ones; they are the same image, so the first wins.
    """
    images = {}
    for path in sorted(glob.glob(os.path.join(root, "**", "*.png"), recursive=True)):
        images.setdefault(os.path.basename(path), path)
    return images


def valid_png(path):
    """Reject truncated or non-PNG payloads before they reach the cache."""
    try:
        with open(path, "rb") as f:
            return f.read(len(PNG_MAGIC)) == PNG_MAGIC
    except OSError:
        return False


def report_incomplete_jobs(run_id, repo, images):
    """Warn about design jobs that produced no image in this run.

    A large run routinely has designs that time out or run out of memory even
    on the bigger runner. Those produce no image, so pruning drops whatever was
    cached for them; say so rather than letting it happen quietly.
    """
    try:
        # fetch_job_results exits on a gh failure; here the job list is only
        # advisory, so downgrade that to a warning and still update the cache.
        results, workflow_name = fetch_job_results(run_id, repo)
    except (SystemExit, Exception) as e:  # noqa: BLE001 - advisory only, never fatal
        print(f"warning: could not read job results ({e})")
        return

    if workflow_name:
        print(f"Run: {workflow_name} ({run_id})")

    incomplete = []
    for (design, target), record in sorted(results.items()):
        # Match an image to its job by design name and the target prefix of the
        # jobname; the jobname extends the target (target "icsprout55_ics55"
        # gives "aes_icsprout55_ics55_stdcell_r.png").
        prefix = f"{design}_{target}"
        if any(name.startswith(prefix) for name in images):
            continue
        incomplete.append((design, target, record))

    if not incomplete:
        return

    print(f"\n{len(incomplete)} design job(s) produced no image in this run:")
    for design, target, record in incomplete:
        state = record["conclusion"] or record["status"] or "unknown"
        step = f" at '{record['failed_step']}'" if record.get("failed_step") else ""
        flag = "!" if state in FAILING_CONCLUSIONS else " "
        print(f"  {flag} {design} / {target}: {state}{step}")


def apply_cache(images, cache_dir, prune, dry_run):
    """Make ``cache_dir`` match ``images``."""
    added, updated, unchanged, pruned = [], [], [], []

    for name, path in sorted(images.items()):
        dest = os.path.join(cache_dir, name)
        if not os.path.exists(dest):
            added.append(name)
        elif filecmp.cmp(path, dest, shallow=False):
            unchanged.append(name)
            continue
        else:
            updated.append(name)
        if not dry_run:
            shutil.copy(path, dest)

    if prune:
        for dest in sorted(glob.glob(os.path.join(cache_dir, "*.png"))):
            name = os.path.basename(dest)
            if name in images:
                continue
            pruned.append(name)
            if not dry_run:
                os.remove(dest)

    verb = "Would" if dry_run else ""
    for label, names in (("add", added), ("update", updated), ("delete", pruned)):
        if not names:
            continue
        heading = f"{verb} {label}" if dry_run else f"{label.capitalize()}d"
        print(f"\n{heading} {len(names)} image(s):")
        for name in names:
            print(f"  {name}")
    if unchanged:
        print(f"\n{len(unchanged)} image(s) already up to date.")

    if not (added or updated or pruned):
        print("\nCache already matches the run; nothing to do.")
    elif dry_run:
        print("\nDry run: no files were changed.")
    else:
        print(f"\nUpdated {os.path.relpath(cache_dir)}; review and commit the changes.")


def main():
    parser = argparse.ArgumentParser(
        description="Replace the cached gallery images with those generated in a CI run.")
    parser.add_argument("run",
                        help="run URL or id to take images from")
    parser.add_argument("--repo",
                        default=DEFAULT_REPO,
                        help=f"repository to look the run up in when the run is given as a "
                             f"bare id (default: {DEFAULT_REPO})")
    parser.add_argument("--no-prune",
                        action="store_true",
                        help="keep cached images the run did not produce instead of "
                             "deleting them")
    parser.add_argument("--dry-run",
                        action="store_true",
                        help="report the changes without writing anything")

    args = parser.parse_args()

    run_id, url_repo = parse_run(args.run)
    repo = url_repo or args.repo

    cache_dir = os.path.normpath(IMAGE_CACHE)
    if not os.path.isdir(cache_dir):
        sys.exit(f"error: image cache directory not found: {cache_dir}")

    print(f"Fetching image artifacts from {repo} run {run_id}")
    live, expired = fetch_image_artifacts(run_id, repo)

    if not live:
        message = f"error: no gallery image artifacts available on run {run_id}"
        if expired:
            message += (f"\n{len(expired)} image artifact(s) have expired "
                        f"(retention is 2 days for '*-image', 7 days for 'images'); "
                        f"re-run the workflow to regenerate them.")
        sys.exit(message)
    if expired:
        print(f"warning: skipping {len(expired)} expired image artifact(s)")

    print(f"Downloading {len(live)} artifact(s)")
    with tempfile.TemporaryDirectory(prefix="scgallery-images-") as tmp:
        download_artifacts(run_id, repo, live, tmp)

        images = collect_images(tmp)
        if not images:
            sys.exit("error: no PNG images found in the downloaded artifacts")

        bad = sorted(name for name, path in images.items() if not valid_png(path))
        for name in bad:
            print(f"warning: skipping {name}: not a valid PNG")
            del images[name]
        if not images:
            sys.exit("error: none of the downloaded images are valid PNGs")

        print(f"Found {len(images)} image(s) in the run")
        report_incomplete_jobs(run_id, repo, images)
        apply_cache(images, cache_dir, not args.no_prune, args.dry_run)

    return 0


if __name__ == "__main__":
    sys.exit(main())
