on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

name: 'Daily CI Tests'

defaults:
  run:
    shell: bash

env:
  REGISTRY: ghcr.io

jobs:
  docker_image:
    name: 'Get docker sc_tools image'
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: read

    outputs:
      sc_tools: ${{ steps.docker.outputs.sc_tools }}

    steps:
      - name: Checkout repository main
        uses: actions/checkout@v3
        with:
          repository: siliconcompiler/siliconcompiler
          path: sc

      - name: Get image name
        id: docker
        run: |
          pip install -r sc/setup/docker/requirements.txt
          sc_tools_name=$(python3 sc/setup/docker/builder.py --tool tools --registry ${{ env.REGISTRY }})
          echo "sc_tools=${sc_tools_name}" >> $GITHUB_OUTPUT

  daily_tests_job:
    needs: docker_image
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.docker_image.outputs.sc_tools }}
      credentials:
        username: ${{ secrets.PACKAGES_ACTOR }}
        password: ${{ secrets.PACKAGES_TOKEN }}

    name: 'All tests'
    steps:
      - name: Checkout SC Gallery
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Gallery
        run: |
          python3 -m venv clean_env
          source clean_env/bin/activate

          python3 -m pip install --upgrade pip
          python3 -m pip install $GITHUB_WORKSPACE.

      - name: Checkout SiliconCompiler
        uses: actions/checkout@v3
        with:
          repository: siliconcompiler/siliconcompiler
          path: siliconcompiler

      - name: Setup Gallery
        run: |
          source clean_env/bin/activate
          cd $GITHUB_WORKSPACE
          export SCPATH=$GITHUB_WORKSPACE/siliconcompiler

          python3 scgallery/run.py -design aes -target freepdk45_demo -gallery ./gallery

      - name: Upload gallery artifacts
        uses: actions/upload-artifact@v3
        with:
          name: gallery
          path: gallery/
          retention-days: 1
